import type { Metadata } from "next";
import { LegalLayout } from "@/components/LegalLayout";
import { PRICE_LABEL } from "@/lib/plans";
import { SITE } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy — Jalees", description: "What Jalees stores about you, who processes it, and how to download or delete it." };

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy">
      <section>
        <h2>Who we are</h2>
        <p>
          Jalees is operated by {SITE.operator}. For anything in this policy, write to {SITE.contactEmail}.
        </p>
      </section>

      <section>
        <h2>What we store</h2>
        <ul>
          <li><strong>Account:</strong> your email address and, if you give one, your name.</li>
          <li><strong>Your practice:</strong> the Arabic you type or say in conversations (for speech, the <em>text</em> that was recognised), the buddy&apos;s replies, the corrections you were given, your recaps, your mistake list and review schedule, and which lesson you are practising.</li>
          <li><strong>Notes you add:</strong> short notes about yourself on the &ldquo;What I remember about you&rdquo; page, and — if you mention them during a session — a few personal details the app picks up (for example why you are learning). You can see and delete every one.</li>
          <li><strong>Usage:</strong> how many seconds of voice you used each day (to apply the daily limit), when you started a free trial, and your placement-test answers.</li>
          <li><strong>Billing:</strong> payments are handled by Stripe. We keep your subscription status and renewal date and Stripe&apos;s identifiers for you — never your card number.</li>
        </ul>
      </section>

      <section>
        <h2>What we do not store</h2>
        <ul>
          <li><strong>Voice recordings.</strong> Audio is sent for transcription and is not saved by Jalees; we keep only the recognised text.</li>
          <li>We do not sell your data, show advertising, or use third-party analytics or tracking cookies.</li>
        </ul>
      </section>

      <section>
        <h2>Who processes it for us</h2>
        <p>We use a small number of service providers to run Jalees. Each handles your data only to provide its service to us:</p>
        <ul>
          <li><strong>Neon</strong> — our database and sign-in service.</li>
          <li><strong>OpenAI</strong> — receives the text you type, the audio you record, and the conversation context so it can write the buddy&apos;s replies, recognise your speech and speak the replies aloud. Please see OpenAI&apos;s own privacy policy for how it handles data sent through its API.</li>
          <li><strong>Stripe</strong> — takes and manages payments.</li>
          <li><strong>Our hosting provider</strong> — runs the website.</li>
        </ul>
        <p>These providers may process data outside your country.</p>
      </section>

      <section>
        <h2>Cookies and local storage</h2>
        <p>We use a sign-in cookie that is necessary for the service to work, and your browser&apos;s local storage to remember whether you prefer the on-screen Arabic keyboard. Nothing is used for tracking.</p>
      </section>

      <section>
        <h2>How long we keep it</h2>
        <p>Until you delete it. When you delete your data from <em>Account &amp; data</em>, we remove your profile, conversations, mistakes, notes, usage, placement results and plan record, cancel any subscription, and close your sign-in account. Stripe keeps its own invoice records as the law requires.</p>
      </section>

      <section>
        <h2>Your choices</h2>
        <ul>
          <li><strong>Download</strong> everything we hold about you as a JSON file from <em>Account &amp; data</em>.</li>
          <li><strong>Delete</strong> it from the same page, at any time, without needing to contact us.</li>
          <li>Depending on where you live you may have further rights (to correct or restrict our use of your data, or to complain to a regulator). Write to {SITE.contactEmail} and we will help.</li>
        </ul>
      </section>

      <section>
        <h2>Children</h2>
        <p>Jalees is not intended for children under 13 (or the higher age required where you live), and we do not knowingly collect their data.</p>
      </section>

      <section>
        <h2>AI and mistakes</h2>
        <p>Replies, corrections and recaps are generated by an AI model and can be wrong. The app limits what the buddy says to the lesson you are on, but it is a practice partner, not a certified grader. Jalees never quotes the Qur&apos;an or hadith and does not give religious guidance.</p>
      </section>

      <section>
        <h2>Changes</h2>
        <p>If we change this policy in a way that matters, we will tell you in the app. The current price of Jalees is {PRICE_LABEL} after a 7-day free trial.</p>
      </section>
    </LegalLayout>
  );
}
